using System.Linq;
using SocialConnector.Entites.EF_DbContext;
using SocialConnector.Entites.Entities;

namespace SocialConnector.Entites.Initializers
{
    public static class SocialDbTestDataSeeder
    {
        private static string[] nationalities = {
            "Afghan"
          , "Albanian"
          , "Algerian"
          , "American"
          , "Andorran"
          , "Angolan"
          , "Antiguans"
          , "Argentinean"
          , "Armenian"
          , "Australian"
          , "Austrian"
          , "Azerbaijani"
          , "Bahamian"
          , "Bahraini"
          , "Bangladeshi"
          , "Barbadian"
          , "Barbudans"
          , "Batswana"
          , "Belarusian"
          , "Belgian"
          , "Belizean"
          , "Beninese"
          , "Bhutanese"
          , "Bolivian"
          , "Bosnian"
          , "Brazilian"
          , "British"
          , "Bruneian"
          , "Bulgarian"
          , "Burkinabe"
          , "Burmese"
          , "Burundian"
          , "Cambodian"
          , "Cameroonian"
          , "Canadian"
          , "Cape Verdean"
          , "Central African"
          , "Chadian"
          , "Chilean"
          , "Chinese"
          , "Colombian"
          , "Comoran"
          , "Congolese"
          , "Costa Rican"
          , "Croatian"
          , "Cuban"
          , "Cypriot"
          , "Czech"
          , "Danish"
          , "Djibouti"
          , "Dominican"
          , "Dutch"
          , "East Timorese"
          , "Ecuadorean"
          , "Egyptian"
          , "Emirian"
          , "Equatorial Guinean"
          , "Eritrean"
          , "Estonian"
          , "Ethiopian"
          , "Fijian"
          , "Filipino"
          , "Finnish"
          , "French"
          , "Gabonese"
          , "Gambian"
          , "Georgian"
          , "German"
          , "Ghanaian"
          , "Greek"
          , "Grenadian"
          , "Guatemalan"
          , "Guinea-Bissauan"
          , "Guinean"
          , "Guyanese"
          , "Haitian"
          , "Herzegovinian"
          , "Honduran"
          , "Hungarian"
          , "I-Kiribati"
          , "Icelander"
          , "Indian"
          , "Indonesian"
          , "Iranian"
          , "Iraqi"
          , "Irish"
          , "Israeli"
          , "Italian"
          , "Ivorian"
          , "Jamaican"
          , "Japanese"
          , "Jordanian"
          , "Kazakhstani"
          , "Kenyan"
          , "Kittian and Nevisian"
          , "Kuwaiti"
          , "Kyrgyz"
          , "Laotian"
          , "Latvian"
          , "Lebanese"
          , "Liberian"
          , "Libyan"
          , "Liechtensteiner"
          , "Lithuanian"
          , "Luxembourger"
          , "Macedonian"
          , "Malagasy"
          , "Malawian"
          , "Malaysian"
          , "Maldivian"
          , "Malian"
          , "Maltese"
          , "Marshallese"
          , "Mauritanian"
          , "Mauritian"
          , "Mexican"
          , "Micronesian"
          , "Moldovan"
          , "Monacan"
          , "Mongolian"
          , "Moroccan"
          , "Mosotho"
          , "Motswana"
          , "Mozambican"
          , "Namibian"
          , "Nauruan"
          , "Nepalese"
          , "New Zealander"
          , "Ni-Vanuatu"
          , "Nicaraguan"
          , "Nigerian"
          , "Nigerien"
          , "North Korean"
          , "Northern Irish"
          , "Norwegian"
          , "Omani"
          , "Pakistani"
          , "Palauan"
          , "Panamanian"
          , "Papua New Guinean"
          , "Paraguayan"
          , "Peruvian"
          , "Polish"
          , "Portuguese"
          , "Qatari"
          , "Romanian"
          , "Russian"
          , "Rwandan"
          , "Saint Lucian"
          , "Salvadoran"
          , "Samoan"
          , "San Marinese"
          , "Sao Tomean"
          , "Saudi"
          , "Scottish"
          , "Senegalese"
          , "Serbian"
          , "Seychellois"
          , "Sierra Leonean"
          , "Singaporean"
          , "Slovakian"
          , "Slovenian"
          , "Solomon Islander"
          , "Somali"
          , "South African"
          , "South Korean"
          , "Spanish"
          , "Sri Lankan"
          , "Sudanese"
          , "Surinamer"
          , "Swazi"
          , "Swedish"
          , "Swiss"
          , "Syrian"
          , "Taiwanese"
          , "Tajik"
          , "Tanzanian"
          , "Thai"
          , "Togolese"
          , "Tongan"
          , "Trinidadian or Tobagonian"
          , "Tunisian"
          , "Turkish"
          , "Tuvaluan"
          , "Ugandan"
          , "Ukrainian"
          , "Uruguayan"
          , "Uzbekistani"
          , "Venezuelan"
          , "Vietnamese"
          , "Welsh"
          , "Yemenite"
          , "Zambian"
          ,"Zimbabwean"
        };

        private static readonly string[] religions = { "Christianity", "Islam", "Hinduism", "Buddhism", "Judaism" };

        public static void Initialize(SocialConnectorDbContext context)
        {
            context.Database.EnsureCreated();

            if (!context.Nationalities.Any())
            {
                foreach (var nationality in nationalities)
                {
                    context.Nationalities.Add(new Nationality { Title = nationality });
                }
                context.SaveChanges();
            }
            if (!context.Genders.Any())
            {
                context.Genders.AddRange(new Gender { Title = "Male" }, new Gender { Title = "Female" });
                context.SaveChanges();
            }
            if (!context.Roles.Any())
            {
                context.Roles.AddRange(new Role { RoleTitle = "User" }, new Role { RoleTitle = "Admin" });
                context.SaveChanges();
            }
            if (!context.Religions.Any())
            {
                foreach(var religion in religions)
                {
                    context.Religions.Add(new Religion { Title = religion });
                }
                context.SaveChanges();
            }
        }
    }
}
